### ISSUE TITLE
Activating rails with empty hand only sometimes works

### ISSUE THREAD

**Issue by CplPibald** [kreezxil/terracart#2]
When you have several open slots on your hotbar, some of them can activate rails and others don't work.

The problem is this line in [RailsClickHandler.java](https://github.com/kreezxil/terracart/blob/master/src/main/java/com/kreezcraft/terracartreloaded/RailsClickHandler.java#L25):

    if ( ... || (event.getEntityPlayer().inventory.getCurrentItem() != ItemStack.EMPTY))

MC 1.12 has multiple ways to set an itemstack to "empty".  For example, placing a block from a stack with size 1 leaves that slot with a stack of size 0, which counts as an empty slot, but is not equal to `ItemStack.EMPTY`.  

The solution is to instead use ItemStack's `isEmpty()` method to detect whether the slot is an empty hand.

    if ( ... || (!event.getEntityPlayer().inventory.getCurrentItem().isEmpty()))

**Comment by kreezxil** [comment]
thank you for the solution, I'll get an update out ASAP (like today)

**Comment by kreezxil** [comment]
1.12.2-1.2.3 fixes this issue. Thanks again.
